### ISSUE TITLE
How can i write latex in blog. Help me. Thank you so much

### ISSUE THREAD

**Issue by ThorPham** [yizeng/jekyll-theme-simple-texture#16]

**Comment by yizeng** [comment]
@ThorPham Did mean using Latex to write articles or add a block of Latex code in an article?

**Comment by ThorPham** [comment]
I  have done it . But i want to change a little. I want to write code python in blog and background is white not black . How can i do that like this code highlight in link :+1: 
https://yous.be/whiteglass/about/
Thank you for your help. Your web is nice. i readly like it

**Comment by yizeng** [comment]
@ThorPham You will need to tweak the highlighter CSS/SASS.

Current theme:
https://github.com/yizeng/jekyll-theme-simple-texture/blob/master/_sass/simple-texture/common/_highlight.scss

Whiteglass Theme:
https://github.com/yous/whiteglass/blob/master/_sass/whiteglass/_syntax-highlighting.scss
