### ISSUE TITLE
How to use without 'home' page

### ISSUE THREAD

**Issue by noritersand** [yizeng/jekyll-theme-simple-texture#26]
Hi! It is very good theme i think. 
However, i want use this theme without 'home' page. (just blog, tags, categories)
Is that possible?

**Comment by yizeng** [comment]
@noritersand 

Yes, absolutely.

Depends on how you are using the theme.

- Use as a fork. This is very easy, you just need to put your own homepage inside `index.html` and remove `_layouts/home.html`. Basically, it's a static site, you can have full control over it.

- Use as a gem. My personal website actually uses a different homepage. Maybe you can have a look there. https://github.com/yizeng/yizeng.me

Cheers!

**Comment by noritersand** [comment]
@yizeng Solved! Thank you. I dont have `_layouts/home.html` file. so, i just put `location.replace('/blog')` script into `index.html`.
