### ISSUE TITLE
How do I add more pages?

### ISSUE THREAD

**Issue by Aspiring-Writer** [yizeng/jekyll-theme-simple-texture#37]
Hello! I really like your theme and it's the only I've found that will work perfectly with this communal site I'm developing, the only thing is I'm not sure how to add more pages or sections (not sure what you call them lol).

The communal site I am developing is for me and some friends to showcase our books. What I want to do is add a section for each book that shows the book cover, description, and author name, how do I do that?

Sorry if this is an easy question with a simple answer, I'm just starting out with web development and Jekyll and don't know a lot.

**Comment by yizeng** [comment]
@Aspiring-Writer Hello! Sorry, it's been too many years that I don't even remember Jekyll myself. I don't really have much to look into this, but you are interested, feel free to check out the source code and take a look.

**Comment by Aspiring-Writer** [comment]
Thanks, I'm actually not using Jekyll right now either.
